import React, { useState } from "react";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";
import { useInsights } from "../../hooks/useInsights";
import { LoadingSpinner } from "../common/LoadingSpinner";
import { IconChevronRight, IconInfoCircle } from "@tabler/icons-react";
import { Link } from "react-router-dom";
import { ROUTES } from "../../utils/constants";

const CustomTooltip = ({ active, payload, label }) => {
  if (!active || !payload || payload.length === 0) {
    return null;
  }

  const formatDate = (dateString) => {
    if (!dateString) return "";
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  };

  return (
    <div className="bg-white p-3 rounded-2xl shadow-lg border border-gray-200">
      <p className="text-gray-900 text-sm font-semibold mb-2">
        {formatDate(label)}
      </p>
      {payload.map((entry, index) => (
        <div key={index} className="flex items-center gap-2">
          <div
            className="w-3 h-3 rounded-full"
            style={{ backgroundColor: entry.color }}
          />
          <span className="text-gray-600 text-xs">
            Mental Health Index:{" "}
            <span className="font-semibold text-gray-900">{entry.value}</span>
          </span>
        </div>
      ))}
    </div>
  );
};

function InsightChart() {
  const { formattedInsights, isLoading, error } = useInsights();
  const [showTooltip, setShowTooltip] = useState(false);

  const formatXAxisDate = (dateString) => {
    if (!dateString) return "";
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    });
  };

  if (isLoading) {
    return (
      <div className="w-full md:w-2/3 h-72 flex items-center justify-center">
        <LoadingSpinner size="sm" />
      </div>
    );
  }

  if (error) {
    return <div className="text-red-500 w-full md:w-2/3 ">{error.message}</div>;
  }

  return (
    <div className="rounded-3xl w-full md:w-2/3 bg-gray-50 p-4 border border-gray-200">
      <div className="mb-4 flex justify-between items-center">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Insight Chart</h1>
          <p className="text-gray-600 text-sm flex items-center gap-1 relative">
            Your mental health index over time.
            <span
              className="text-gray-500 text-xs"
              onClick={() => setShowTooltip(!showTooltip)}
            >
              <IconInfoCircle className="w-4 h-4" />
            </span>
            {showTooltip && (
              <div className="absolute top-full left-0 leading-relaxed max-w-xs bg-white z-40 px-2 py-4 rounded-lg shadow-lg border border-gray-200">
                <p className="text-gray-600 text-xs">
                  This index measures your mental health over time from the
                  insights generated by your conversations with the AI
                  therapist. A high index indicates bad mental health, while a
                  low index indicates good mental health.
                </p>
              </div>
            )}
          </p>
        </div>
        <Link
          to={ROUTES.INSIGHTS}
          className="flex items-center gap-1 text-sm text-gray-600 hover:text-gray-900"
        >
          More
          <IconChevronRight className="w-4 h-4" />
        </Link>
      </div>
      <ResponsiveContainer width="100%" height={300} className="">
        <AreaChart
          width={500}
          height={300}
          data={formattedInsights}
          margin={{ left: -15, right: 10, top: 10, bottom: 10 }}
        >
          <defs>
            <linearGradient id="colorGradient" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="#8884d8" stopOpacity={0.8} />
              <stop offset="100%" stopColor="#8884d8" stopOpacity={0.1} />
            </linearGradient>
          </defs>
          <XAxis
            dataKey="createdAt"
            tickFormatter={formatXAxisDate}
            tick={{ fontSize: 12, fill: "#6B7280" }}
            textAnchor="middle"
            height={60}
          />
          <YAxis
            width={40}
            tick={{ fontSize: 14, fontWeight: 600, fill: "#374151" }}
          />
          <CartesianGrid stroke="#ccc" strokeDasharray="5 5" />
          <Tooltip content={<CustomTooltip />} />
          <Area
            type="monotone"
            dataKey="index"
            stroke="#8884d8"
            fill="url(#colorGradient)"
          />
        </AreaChart>
      </ResponsiveContainer>
    </div>
  );
}

export default InsightChart;
